import React from 'react';
import BackButton from './BackButton';

export default function RiskScoreInfo() {
  return (
    <div className="foulpay-app-container foulpay-page-with-footer">
      <div className="foulpay-content">
        <h1 className="foulpay-title">Understanding the Risk Score</h1>

        <div className="foulpay-description">
          <p>
            The <strong>Risk Score</strong> is a number from 0 to 100 that indicates how likely a transaction is to be fraudulent,
            based on patterns in historical data. It’s generated by an anomaly detection model trained on real transaction behaviors.
          </p>
        </div>

        <div className="foulpay-risk-info">
          <h3>🔢 Score Breakdown</h3>
          <ul>
            <li><strong>0–50:</strong> Low Risk — matches typical user behavior; likely safe.</li>
            <li><strong>51–80:</strong> Medium Risk — partially unusual; should be reviewed.</li>
            <li><strong>81–100:</strong> High Risk — major deviation from norms; strong fraud signal.</li>
          </ul>
        </div>

        <div className="foulpay-risk-info">
          <h3>📊 How It’s Calculated</h3>
          <ul>
            <li>We use anomaly detection algorithms like autoencoders or Isolation Forests.</li>
            <li>Each transaction is compared to a learned model of “normal” behavior.</li>
            <li>The further it deviates, the higher the risk score.</li>
          </ul>
        </div>

        <div className="foulpay-risk-info">
          <h3>💡 Why It Matters</h3>
          <ul>
            <li>High scores allow companies to stop fraud in real-time.</li>
            <li>Low scores help reduce false alarms and customer friction.</li>
            <li>It’s part of a broader fraud detection pipeline.</li>
          </ul>
        </div>
      </div>

      <div className="foulpay-footer">
        <BackButton />
      </div>
    </div>
  );
}
